export const storeProducts = [
{
    id: 1,
    title: 'Aloo Paratha',
    img: "images/alooParatha.jpg",
    price: 100,
    category: "1",
    time: '20-25 mins',
    info: "Aloo Paratha is a delicious shallow fried flaky bread, stuffed with mashed boiled potaoes, grated ginger, cilantro, cut chillies. These crispy prathas are generally fried with ghee.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 2,
    title: 'Aloo Tikki',
    img: "images/alooTikki.jpg",
    price: 55,
    category: "1",
    time: '10-15 mins',
    info: "These are deep-fried, very thin, salted slices of potato that are usually served at room temperature. French fries have numerous variants, from thick-cut to shoestring, crinkle, curly and many other names. They are readily available at restaurants or Mac Donald outlet",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 3,
    title: 'Bread Pakoda',
    img: "images/breadPakoda.jpg",
    price: 120,
    category: "1",
    time: '5-10 mins',
    info: "Bread Pakodas are tasty,crunchy deep-fried treats . These are made from paneer slices stuffed with Indian herbs and spices, dipped in gram flour batter and deep fried.They taste perfect with mint chutney .",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 4,
    title: 'Chhole Bhature',
    img: "images/chholeBhature.jfif",
    price: 60,
    category: "1",
    time: '25-30 mins',
    info: "Bhatura is classic Indian deep fried puffed bread which is always associated with inseparable masala Chole. It is made from all purpose flour, yeast and vegetable oil. ",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 5,    
    title: 'Zucchini',
    img: "images/Zucchini.png",
    price: 100,
    category: "0",
    time: '30-40 mins',
    info: "Green, cylindrical squash are what most people think of when they think of zucchini, but the color can vary from a solid, deep green, to lighter shades with streaks or blotches of darker green. ",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 6,
    title: 'Sandwich',
    img: "images/sandwich.jpg",
    price: 100,
    category: "1",
    time: '10-15 mins',
    info: "Sandwich Pakodas are tasty,crunchy deep-fried treats . These are made from paneer slices stuffed with Indian herbs and spices, dipped in gram flour batter and deep fried.They taste perfect with mint chutney .",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 7,
    title: 'Dosa',
    img: "images/dosa.jpg",
    price: 200,
    category: "1",
    time: '20-25 mins',
    info: "Sambar, brimful of the goodness of toovar dal and assorted vegetables, it is nutritious everyday fare and is so versatile that it can be taken with dosa.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 8,
    title: 'Idli',
    img: "images/idli.jpg",
    price: 150,
    category: "1",
    time: '30-35 mins',
    info: "Idli is a south Indian savory cake popular throughout India. The cakes are made by steaming a batter consisting of fermented black lentils and rice. It is served with Sambhar and chutney.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 9,    
    title: 'Grilled Barbecue',
    img: "images/grilledBarbecue.png",
    price: 120,
    category: "0",
    time: '35-40 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 10,
    title: 'Noodles',
    img: "images/noodles.jpg",
    price: 80,
    category: "1",
    time: '15-20 mins',
    info: "Vegetable Noodles are madein chinese style by using boiled noodles, stir fried with vegetables like carrots, cabbage, beans with soy sauce.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 11,
    title: 'White Sauce Pasta',
    img: "images/pasta.jpg",
    price: 50,
    category: "1",
    time: '30-35 mins',
    info: "The creamy flavour of white sauce pasta may tingle your taste buds, pasta with canned diced tomatoes just after it's cooked.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 12,
    title: 'Patties',
    img: "images/patties.jpg",
    price: 70,
    category: "1",
    time: '10-20 mins',
    info: "Potato patties is a shallow fried cutlet with the boiled and mashed potatoes. The potato patties can be enjoyed as a filling for sandwiches, as a snack with chutney or as burger.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 13,
    title: 'Pav Bhaji',
    img: "images/pavBhaji.jpg",
    price: 110,
    category: "1",
    time: '20-25 mins',
    info: "A spicy curry of mixed vegetables cooked in a special blend of spices and served with soft buttered",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 14,
    title: 'Rajma Chawal',
    img: "images/rajmachawal.jpg",
    price: 70,
    category: "1",
    time: '30-40 mins',
    info: "Delight for vegetarians, fresh cooked biryani with chunks of tandoori cottage cheese tikka",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 15,
    title: 'Red Sauce Pasta',
    img: "images/redSaucePasta.jpg",
    price: 80,
    category: "1",
    time: '20-25 mins',
    info: "Hungree Belly adaptation of the Italian classic, flavourful tomato sauce and cheesy",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 16,
    title: 'Samosa',
    img: "images/samosa.jpg",
    price: 20,
    category: "1",
    time: '10-15 mins',
    info: "Crispy pastry stuffed with spiced potatoes and peas.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 17,
    title: 'Pizza',
    img: "images/pizza.png",
    price: 90,
    category: "1",
    time: '25-30 mins',
    info: "No sauce, mozzarella, parmesan, garlic, oregano, and olive oil. Made with grande cheese and Caputo blue.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 18,
    title: 'Coffee',
    img: "images/coffee.jpg",
    price: 70,
    category: "1",
    time: '30-40 mins',
    info: "The coffee has a crisp, bright flavor, with subtle hints of citrus and rich chocolates.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 19,
    title: 'Tea',
    img: "images/tea.jpg",
    price: 40,
    category: "1",
    time: '5-10 mins',
    info: "Tea is bright in colour and greater in flavor and freshness, and thus is the most sought after.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 20,
    title: 'French Fries',
    img: "images/frenchFries.png",
    price: 90,
    category: "1",
    time: '10-20 mins',
    info: "These are deep-fried, very thin, salted slices of potato that are usually served at room temperature. French fries have numerous variants, from thick-cut to shoestring, crinkle, curly and many other names. They are readily available at restaurants or Mac Donald outlets",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 21,
    title: 'Chocolate Cake',
    img: "images/chocolateCake.png",
    price: 120,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of chocolate cake and chocolate mousse are topped with dark chocolate ganache and finished with a generous sprinkling of chocolate shavings.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 22,
    title: 'veg',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRwpQNTdG8F4LLUOibUMQXeYmAqHoZbAaQz5w&usqp=CAU",
    price: 110,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of chocolate cake and chocolate mousse are topped with dark chocolate ganache and finished with a generous sprinkling of chocolate shavings.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 23,
    title: 'veg',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQVdgqsCqiZYkCbFK8Pd9EJoKOdkwcfZvW7Vw&usqp=CAU",
    price: 100,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of chocolate cake and chocolate mousse are topped with dark chocolate ganache and finished with a generous sprinkling of chocolate shavings.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 24,
    title: 'veg',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSx0xlisCKZZRE7WJnPHYwp6sEranTKyU2Ulg&usqp=CAU",
    price: 60,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of chocolate cake and chocolate mousse are topped with dark chocolate ganache and finished with a generous sprinkling of chocolate shavings.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 25,
    title: 'veg',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTPD1DbmKfvjzay4g6WLzk_W7hvH3zTi9P0wQ&usqp=CAU",
    price: 80,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of chocolate cake and chocolate mousse are topped with dark chocolate ganache and finished with a generous sprinkling of chocolate shavings.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 26,
    title: 'veg',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSx0xlisCKZZRE7WJnPHYwp6sEranTKyU2Ulg&usqp=CAU",
    price: 90,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of chocolate cake and chocolate mousse are topped with dark chocolate ganache and finished with a generous sprinkling of chocolate shavings.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 27,
    title: 'veg',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTPD1DbmKfvjzay4g6WLzk_W7hvH3zTi9P0wQ&usqp=CAU",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of chocolate cake and chocolate mousse are topped with dark chocolate ganache and finished with a generous sprinkling of chocolate shavings.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 28,
    title: 'veg misal',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQnZ6GSvAvGiglD0fciBjP9QigoCB1mp9V3qQ&usqp=CAU",
    price: 620,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers spicy masala and samber , mixture of spicy test",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 29,
    title: 'veg bhel',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR5csvDvMTQhuuBePZyGCmTAwWe03IFKAkt8Q&usqp=CAU",
    price: 80,
    category: "1",
    time: '25-30 mins',
    info: "spicy bhel with lots of masala...! enjoy it now..!.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 30,
    title: 'veg mix',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRwpQNTdG8F4LLUOibUMQXeYmAqHoZbAaQz5w&usqp=CAU",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of fresh  vegitables with spicy test ganache and finished with a generous sprinkling of bhajji shavings.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 31,
    title: 'veg kurma',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTPD1DbmKfvjzay4g6WLzk_W7hvH3zTi9P0wQ&usqp=CAU",
    price: 85,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of fresh  vegitables with spicy test.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 32,
    title: 'veg thali',
    subtitle:'dishname',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSx0xlisCKZZRE7WJnPHYwp6sEranTKyU2Ulg&usqp=CAU",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "pure veg thali with 4 chapatee , 1 bowl rice, samber, bhajji, papad",
    inCart: false,
    count: 0,
    total: 0
},
//South Indian
{
    id: 33,
    title: 'veg Avial (South Indian)',
    subtitle:'Avial',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Sambar%26Avial.jpg/120px-Sambar%26Avial.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Coconut paste, curd mixed with vegetables and some spices.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 34,
    title: 'veg Bisi bele bath(Karnataka,(South Indian))',
    subtitle:'Bisi bele bath',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Bisi_Bele_Bath.jpg/120px-Bisi_Bele_Bath.jpg",
    price: 65,
    category: "1",
    time: '25-30 mins',
    info: "Rice preparation with vegetables.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 35,
    title: 'veg Bonda (South Indian)',
    subtitle:'Bonda',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Bonda2.jpg/120px-Bonda2.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Snack. Potatoes, gram flour.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 36,
    title: 'veg Dosa (South Indian)',
    subtitle:'Dosa',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Dosa-chutney-sambhar.jpg/120px-Dosa-chutney-sambhar.jpg",
    price: 75,
    category: "1",
    time: '25-30 mins',
    info: "Pancake/Hopper. Ground rice, urad dal",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 37,
    title: 'veg Double ka meetha (South Indian)',
    subtitle:'Double ka meetha',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/1/17/DoubleKaMeetha.JPG/120px-DoubleKaMeetha.JPG",
    price: 65,
    category: "1",
    time: '25-30 mins',
    info: "Bread crumbs fried in ghee and dipped in milk and sugar syrup",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 38,
    title: 'veg Idiappam(Tamil Nadu, (South Indian))',
    subtitle:'Idiappam(Tamil Nadu)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/0/04/Idiyappam.jpg/120px-Idiyappam.jpg",
    price: 98,
    category: "1",
    time: '25-30 mins',
    info: "Steamed rice noodles or vermicelli with Ground rice",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 39,
    title: 'veg Idli (South Indian)',
    subtitle:'Idli',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/1/11/Idli_Sambar.JPG/120px-Idli_Sambar.JPG",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Steamed cake of fermented rice and pulse flour. Rice, urad dal",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 40,
    title: 'veg Kanji (South Indian)',
    subtitle:'Kanji',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/5/58/Chinese_rice_congee.jpg/120px-Chinese_rice_congee.jpg",
    price: 205,
    category: "1",
    time: '25-30 mins',
    info: "a rice porridge",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 41,
    title: 'NonVeg Kerala_Beef_Fry (South Indian)',
    subtitle:'Kerala_Beef_Fry',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/%E0%B4%AC%E0%B5%80%E0%B4%AB%E0%B5%8D%E0%B4%AB%E0%B5%8D%E0%B4%B0%E0%B5%88.jpg/220px-%E0%B4%AC%E0%B5%80%E0%B4%AB%E0%B5%8D%E0%B4%AB%E0%B5%8D%E0%B4%B0%E0%B5%88.jpg",
    price: 145,
    category: "0",
    time: '25-30 mins',
    info: "Beef, onions, spices, coconut, curry leaves",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 42,
    title: 'veg Koottu (South Indian)',
    subtitle:'koottu',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Cabbage_kootu.jpg/120px-Cabbage_kootu.jpg",
    price: 45,
    category: "1",
    time: '25-30 mins',
    info: "Vegetable, daal or lentil mixture boiled in water",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 43,
    title: 'veg Kuzhakkattai(South Indian)',
    subtitle:'Kuzhakkattai',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Kozhukkatta.jpg/120px-Kozhukkatta.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Dumplings with Rice flour, jaggery, and coconut",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 44,
    title: 'veg Masala Dosa (South Indian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/3/34/Masala_Dosa_with_Aloo_masala.jpg/120px-Masala_Dosa_with_Aloo_masala.jpg",
    price: 125,
    category: "1",
    time: '25-30 mins',
    info: "Dosa with masala and potato.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 45,
    title: 'veg Obbattu (holige, bobbattu, pooran-poli)(South Indian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/7/71/Obbattu.jpg/120px-Obbattu.jpg",
    price: 45,
    category: "1",
    time: '25-30 mins',
    info: "A stuffed (moong gram dal and jaggery or coconut poornam) paratha. Dish native to South and West India in the states of Karnataka, Andhra Pradesh and Maharashtra Vegetarian.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 46,
    title: 'veg Pongal(South Indian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Pongali.JPG/120px-Pongali.JPG",
    price: 45,
    category: "1",
    time: '25-30 mins',
    info: "Pongal Pulao.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 47,
    title: 'veg Thayir sadam, mosaranna(South Indian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Curd_rice_and_hummus.jpg/120px-Curd_rice_and_hummus.jpg",
    price: 45,
    category: "1",
    time: '25-30 mins',
    info: "Dosa a curd rice dish.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 48,
    title: 'veg Uttapam(South Indian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/1/14/Indian_Pancake.jpg/120px-Indian_Pancake.jpg",
    price: 85,
    category: "1",
    time: '25-30 mins',
    info: "Rice pancake/hopper with a topping of onions / tomatoes / coconut.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 49,
    title: 'veg Vada(South Indian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/1/10/Vada_2.jpg/120px-Vada_2.jpg",
    price: 65,
    category: "1",
    time: '25-30 mins',
    info: "Savory donut. Urad dal..",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 50,
    title: 'veg Wheat upma(South Indian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/1/16/Upma.jpg/120px-Upma.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "A breakfast dish and snack. Upma prepared from wheat dhalia rava.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 51,
    title: 'veg Modak(Maharashtiran)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/MMutta-_Savouries1.JPG/120px-MMutta-_Savouries1.JPG",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "	Sweet coconut dumplings. Rice flour, coconut.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 52,
    title: 'veg Shankarpali(Maharashtiran)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Shankarpali_sweets_mithai_Western_India_2012.jpg/120px-Shankarpali_sweets_mithai_Western_India_2012.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Sweet or savoury snack. Plain flour, sugar.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 53,
    title: 'veg Shrikhand(Maharashtiran)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Shrikhand_london_kastoori.jpg/120px-Shrikhand_london_kastoori.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "A thick yogurt-based sweet dessert garnished with ground nuts, cardamom, and saffron.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 54,
    title: 'veg Gajar halwo sweet',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/4/42/Gajjar_ka_halwa_%28carrot_halwa%29.JPG/120px-Gajjar_ka_halwa_%28carrot_halwa%29.JPG",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Sweet. Carrot Halwa.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 57,
    title: 'veg Gulab jamun sweet',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/5/56/Gulab_Jamun.jpg/120px-Gulab_Jamun.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Sweet. Gulab jamun.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 55,
    title: 'veg Pohe(maharashtiran)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Poha%2C_a_snack_made_of_flattened_rice.jpg/120px-Poha%2C_a_snack_made_of_flattened_rice.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "A breakfast dish Snack. Flattened rice.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 56,
    title: 'veg Dum aaloo(north Indian)',
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Kashmiri_Dum_Aaloo.JPG/320px-Kashmiri_Dum_Aaloo.JPG",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Main dish. Potatoes deep fry, yogurt, coriander powder, ginger powder.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 58,
    title: 'veg Dabeli(maharashtrian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/6/63/Dabeli.jpg/220px-Dabeli.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Snack made by mixing boiled potatoes with a special dabeli masala, putting the mixture in a ladi pav.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 59,
    title: 'veg Dhokala(Rajasthani)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/0/08/Khaman_dhokla.jpg/120px-Khaman_dhokla.jpg",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Lentil snack. Gram.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 60,
    title: 'veg DahiVada(maharashtrian)',
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/3/34/Dahi_Vadas_%28Dhai_Bhalla%29.JPG/120px-Dahi_Vadas_%28Dhai_Bhalla%29.JPG",
    price: 95,
    category: "1",
    time: '25-30 mins',
    info: "Fried lentil balls in a yogurt sauce. Lentils, yogurt.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 61,
    title: 'NonVeg Ande Ka Salan Tangy Egg Masala in Peanut Gravy',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSNcFM86iKcUKvOKSU2vsfsXoUT7JeGxAaUKg&usqp=CAU",
    price: 175,
    category: "0",
    time: '25-30 mins',
    info: "Ande Ka Salan Recipe is a tangy, spicy curry prepared using coconut based gravy and hard boiled eggs",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 62,
    title: 'NonVeg Bengali Style Pomfret Shorshe Pomfret In Mustard Gravy',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQEvO0zQDm_r0ANZ4DcsjxGDdmhTCJi2srOBw&usqp=CAU",
    price: 195,
    category: "0",
    time: '25-30 mins',
    info: "Mustard sauce gravy can be used to cook other fishes like hilsa, rohu, catla, catfish and various other river fishes. The usage of mustard oil and mustard paste is what makes Pomfret Shorshe heavenly when had with hot white rice.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 63,
    title: 'NonVeg Kerala Egg Roast Masala',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQKvXF5UOSTaIaAAYPw1zF7yV93zGynXoWb-w&usqp=CAU",
    price: 145,
    category: "0",
    time: '25-30 mins',
    info: "Kerala Egg Roast Masala Recipe is a delicious spicy preparation of the eggs in a delicious onion and tomato based gravy that is delicately cooked in coconut oil adding the authentic taste.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 64,
    title: 'NonVeg Malabar Mutton Roast',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTYDGdRfjE_yXWS-E5-j6PApiipZiHQNQSVgQ&usqp=CAU",
    price: 185,
    category: "0",
    time: '25-30 mins',
    info: "Mutton Varattiyathu Recipe is a Malabar style Mutton Roast, marinated along with simple spices and stir fried to give it a lovely roasted flavour.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 65,
    title: 'NonVeg Bengali Style Mangsher Jhol-Mutton Curry',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR97EGQUbNr4UMAlVW1K9mHxSRv2xc3_8-IDA&usqp=CAU",
    price: 150,
    category: "0",
    time: '25-30 mins',
    info: "Mangsher Jhol’ and Sundays are synonymous in Bengali kitchen.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 66,
    title: 'NonVeg mutton curry',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRh9KL5CEt3PXvEFM9TzsBtnwRsOCmmvAdNtw&usqp=CAU",
    price: 135,
    category: "0",
    time: '25-30 mins',
    info: "mutton curry..",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 67,
    title: 'NonVeg eggs',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQMxhhsKCOglsZAJC1oal16l2xyDYjKIhkbwQ&usqp=CAU",
    price: 145,
    category: "0",
    time: '25-30 mins',
    info: "Beef, onions, spices, coconut, curry leaves",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 68,
    title: 'NonVeg Mutton In Red Spicy Gravy Rajasthani Laal Maas',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGrNzQnirCqHl8VEzo3PtQf1CaqkgN0pLG8g&usqp=CAU",
    price: 145,
    category: "0",
    time: '25-30 mins',
    info: "Laal Maas is a very popular non-veg recipe in Rajasthan. It is a fiery meat curry which is made with the combination of Kashmiri red chillies and other popular spices of Rajasthan.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 69,
    title: 'NonVeg Fish Tandoori Recipe',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQlPVLM-QWYcVbt3hI2SYbMi3IEpaLke1WX3Q&usqp=CAU",
    price: 165,
    category: "0",
    time: '25-30 mins',
    info: "Have you ever tried out fish tandoori? Trust me, it is equally as delicious as chicken tandoori. Normally, tandoori is prepared in tandoor oven, but I normally prepare it in my convection oven",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 70,
    title: 'NonVeg Mutton Chops Curry',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQgkL2jr19mTu-rTcm025CCIVNp1VYUC5anmw&usqp=CAU",
    price: 145,
    category: "0",
    time: '25-30 mins',
    info: "Chettinad Mutton Chops Kuzhambu is a spicy and delicious mutton chops dish which has a twist of flavor packed Chettinad style curry.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 71,
    title: 'NonVeg Mushroom Masala Cheese Omelette',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRC774NRY_Yo1dfZ_qahxzu1GFbf3giymZCcw&usqp=CAU",
    price: 145,
    category: "0",
    time: '25-30 mins',
    info: "Mushroom Masala Cheese Omelette Recipe is a wholesome and high protein omelette that is packed with taste from mushrooms, green chillies and coriander.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 72,
    title: 'NonVeg Crispy and Spicy Chilli Chicken- Indian Style',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTwYVxns87Nn4byY5M3G9Y0KM7SqfuzFRHmVw&usqp=CAU",
    price: 125,
    category: "0",
    time: '25-30 mins',
    info: "Made with Indian spices and a generous topping of fried onions and curry leaves  Chicken is marinated for long in a plethora of spices and then is deep fried and adorned with fried onions and curry leaves. ",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 73,
    title: 'NonVeg Dum Pukht Gosht  - Slow Cooked Mutton Curry',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQEvO0zQDm_r0ANZ4DcsjxGDdmhTCJi2srOBw&usqp=CAU",
    price: 175,
    category: "0",
    time: '25-30 mins',
    info: "Dum Pukht is a slow cooking technique where food is cooked in a sealed vessel. Dum means to breathe and Pukht means to cook.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 74,
    title: 'NonVeg Egg Korma',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS4ISq9ZqMD8Sr58NC0HU5WQzDVeyHxMLDAWw&usqp=CAU",
    price: 185,
    category: "0",
    time: '25-30 mins',
    info: "Egg Korma an easy recipe and it gives a twist to our normal egg curry with coconut milk, and spiced with garam masala, ginger garlic, cumin powder, coriander powder and more",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 75,
    title: 'NonVeg Broccoli Egg Bhurji',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLS7JcMbjM2RVWujDGhAjX-KFV5AJQQAl12Q&usqp=CAU",
    price: 145,
    category: "0",
    time: '25-30 mins',
    info: "Egg is one such versatile food which can be paired with any vegetable and a delicious recipe can be prepared. Broccoli Egg Bhurji is one such recipe, which is a combination of scrambled eggs and broccoli.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 76,
    title: 'NonVeg Delicious Breakfast Anda Ghotala Recipe With Butter Pav',
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQRFSdblvsZm9pTm7yEoEHkKriVfWi2m-cSCQ&usqp=CAU",
    price: 245,
    category: "0",
    time: '25-30 mins',
    info: "They eggs added to the anda ghotala are scrambled eggs, boiled eggs and fried eggs.  Anda ghotala is a popular street food recipe in Surat and now is making its way to the street food in Mumbai and Pune. It is a high protein dish and is loved by people of all ages. Anda Ghotala can be served on its own or along with some pav slathered with butter ",
    inCart: false,
    count: 0,
    total: 0
},

];

export const detailProduct = {
    id: 1,
    title: 'Sandwich',
    img: "images/sandwich.jpg",
    price: 100,
    category: "1",
    time: '10-15 mins',
    info: "Sandwich Pakodas are tasty,crunchy deep-fried treats . These are made from paneer slices stuffed with Indian herbs and spices, dipped in gram flour batter and deep fried.They taste perfect with mint chutney .",
    inCart: false,
    count: 0,
    total: 0
};

